baseurl = "https://nateaff.com/"
relativeurls = true
languageCode = "en-us"
title = "Nathanael Aff"
theme = "hugo-theme-minos"
googleAnalytics = "UA-103620819-1"
disqusShortname = "nateaff-com"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Projects"
    url = "projects"
[[menu.main]]
    name = "About"
    url = "about"

[params]
    katex = true
    description = "Data, math, programming"
    fontbody = "Noto Serif"
    fontheading = "Lato"
    smartToc = true
   