baseurl = "http://nateaff.com/"
relativeurls = true
languageCode = "en-us"
title = "Nathanael Aff"
theme = "hugo-theme-minos"
googleAnalytics = "UA-103620819-1"
disqusShortname = "nateaff-com"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Projects"
    url = "projects"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/nateaff"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/nateaff"


[params]
    katex = true
    description = "A data, math, and programming blog"
    fontbody = "Amiri"
    fontheading = "Lato"
    smartToc = true
