baseurl = "https://nateaff.com/"
relativeurls = true
languageCode = "en-us"
title = "Nathanael Aff"
theme = "hugo-theme-minos"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/nateaff"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/nateaff"

[params]
    katex = true
    description = "A website built through Hugo and blogdown."

